AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  AWS Translator Pipeline for https://github.com/vidura-95/AWS_Translator
  Flow: GitHub doc -> input S3 -> Lambda (Textract+Comprehend+Translate) -> output S3.
  Deploy: sam build && sam deploy --guided.[web:28][attached_file:1]

Parameters:
  GitHubFileUrl:
    Type: String
    Default: "https://raw.githubusercontent.com/vidura-95/AWS_Translator/main/sample.pdf"
    Description: |
      UPDATE THIS: Raw URL of document in your repo to translate.
      - Add sample.pdf to repo root & push.
      - Or use README.md: https://raw.githubusercontent.com/vidura-95/AWS_Translator/main/README.md
      - Test: sam deploy --parameter-overrides GitHubFileUrl=your-url-here
  InputBucketName:
    Type: String
    Default: "aws-translator-input-vidura95"
    Description: |
      UPDATE THIS: Make unique with your AWS account ID.
      Run `aws sts get-caller-identity` → append Account: aws-translator-input-vidura95-123456789012
  OutputBucketName:
    Type: String
    Default: "aws-translator-output-vidura95"
    Description: |
      UPDATE THIS: Make unique, e.g., aws-translator-output-vidura95-123456789012
  TargetLanguageCode:
    Type: String
    Default: "de"
    Description: Target lang (de=German, fr=French, es=Spanish). https://docs.aws.amazon.com/translate/latest/dg/what-is.html
  FetchSchedule:
    Type: String
    Default: "rate(1 hour)"
    Description: |
      Edit for testing: "rate(5 minutes)" or "cron(0/5 * * * ? *)"
  LambdaTimeoutSeconds:
    Type: Number
    Default: 900
    Description: Max 900s for large docs (Textract async possible later).

Globals:
  Function:
    Runtime: python3.12
    Timeout: !Ref LambdaTimeoutSeconds
    MemorySize: 2048  # Increased for Textract
    Environment:
      Variables:
        TARGET_LANGUAGE_CODE: !Ref TargetLanguageCode
        OUTPUT_BUCKET: !Ref DocOutputBucket

Resources:
  DocInputBucket:
    Type: AWS::S3::Bucket
    BucketName: !Ref InputBucketName
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt ProcessDocumentFunction.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: ".pdf"  # EDIT: Add ".png,.jpg,.txt" if needed
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  DocOutputBucket:
    Type: AWS::S3::Bucket
    BucketName: !Ref OutputBucketName
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  GitHubFetchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/github_fetch/
      Handler: app.lambda_handler
      Description: Pulls doc from vidura-95/AWS_Translator GitHub repo to input S3.
      Environment:
        Variables:
          GITHUB_FILE_URL: !Ref GitHubFileUrl
          INPUT_BUCKET: !Ref DocInputBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref DocInputBucket
      Events:
        ScheduledFetch:
          Type: EventBridgeRule
          Properties:
            ScheduleExpression: !Ref FetchSchedule
            State: ENABLED

  ProcessDocumentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/process_document/
      Handler: app.lambda_handler
      Description: Textract text → Comprehend analysis → Translate → output S3.
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DocInputBucket
        - S3WritePolicy:
            BucketName: !Ref DocOutputBucket
        - Statement:
            Effect: Allow
            Action:
              - textract:DetectDocumentText
              - textract:AnalyzeDocument  # For tables/forms
            Resource: "*"
        - Statement:
            Effect: Allow
            Action:
              - comprehend:DetectDominantLanguage
              - comprehend:DetectEntities
              - comprehend:DetectSentiment
            Resource: "*"
        - Statement:
            Effect: Allow
            Action:
              - translate:TranslateText
            Resource: "*"
      Architectures:
        - arm64  # Cost-effective; change to x86_64 if issues

  S3InvokeProcessPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ProcessDocumentFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt DocInputBucket.Arn

Outputs:
  StackUrl:
    Description: "Deployed! Test: Invoke GitHubFetchFunction manually."
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/lambda/home?region=${AWS::Region}/#/functions/${GitHubFetchFunction}?tab=configuration"
  InputBucket:
    Value: !Ref DocInputBucket
  OutputBucket:
    Value: !Ref DocOutputBucket
  GitHubFetchArn:
    Value: !GetAtt GitHubFetchFunction.Arn
